services:
  zenith:
    build:
      context: .
      args:
        USERNAME: phil
        USER_UID: "${UID}"
        USER_GID: "${GID}"
    user: "${UID}:${GID}"
    network_mode: host
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    working_dir: /ros2_ws
    volumes:
      - ./ros2_ws:/ros2_ws:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-/home/phil/.Xauthority}:/home/phil/.Xauthority:ro
    environment:
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/phil/.Xauthority
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: >
      bash -lc "
        source /opt/ros/humble/setup.bash &&
        colcon build &&
        ros2 daemon start &&
        source install/setup.bash &&
        ros2 launch mavros apm.launch fcu_url:=tcp://127.0.0.1:5763 &
        tail -f /dev/null
      "